### ISSUE TITLE
Make `Uuid` implement `Copy`

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/uuid#33]
This will improve ergonomics a little, thoughts?

**Comment by sinistersnare** [comment]
+1. If this happens, I can make the change.

**Comment by alexcrichton** [comment]
This was also proposed in https://github.com/rust-lang/uuid/pull/21 and https://github.com/rust-lang/uuid/pull/20, but at this point I think it's pretty clear that we won't be representing a `Uuid` any differently, so I'd be fine adding a `Copy` impl :)
